image: circleci/openjdk:17-buster-node

cache:
  paths:
    - .m2/repository
variables:
  MAVEN_REPO_URL: "${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/maven"

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo $MAVEN_REPO_URL
    - echo $DEPLOY_GITLAB_TOKEN
    - 'curl --header "Private-Token: ${DEPLOY_GITLAB_TOKEN}" "${MAVEN_REPO_URL}"'
    - mvn clean install -s ci_settings.xml
    - mvn -X deploy -s ci_settings.xml
  only:
    - main
