image: circleci/openjdk:17-buster-node

cache:
  paths:
    - .m2/repository

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo $Deploy_Token
    - mvn clean install -s ci_settings.xml
    - mvn -X deploy -s ci_settings.xml
  only:
    - main
