image: circleci/openjdk:17-buster-node

cache:
  paths:
    - .m2/repository

stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s ci_settings.xml"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install

deploy:
  stage: deploy
  script:
    - 'mvn deploy -s ci_settings.xml'
  only:
    - main
