image: circleci/openjdk:17-buster-node

cache:
  paths:
    - .m2/repository

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Setting up environment variables..."
    - MAVEN_REPO_URL="${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/maven"
    - echo "MAVEN_REPO_URL=${MAVEN_REPO_URL}"
    - 'curl --header "Private-Token: ${Deploy_Token}" "${MAVEN_REPO_URL}"'
    - mvn clean install -s ci_settings.xml
    - mvn -X deploy -s ci_settings.xml
  only:
    - main
