image: circleci/openjdk:17-buster-node

cache:
  paths:
    - .m2/repository

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - 'echo "Private-Token: ${Deploy_Token}" "${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/maven"'
    - 'curl --header "Private-Token: ${Deploy_Token}" "${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/packages/maven"'
    - mvn clean install -s ci_settings.xml
    - mvn -X deploy -s ci_settings.xml
  only:
    - main
