image: circleci/openjdk:17-buster-node

stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s ci_settings.xml"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image: maven:3.6-jdk-11
  script:
    - 'mvn deploy $MAVEN_CLI_OPTS'
  only:
    - main
