name: openHAB CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: maven:3.8.4-openjdk-11

    steps:
    - name: Install Node.js
      run: |
        apt-get update
        apt-get install -y curl
        curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        apt-get install -y nodejs
    
    - uses: actions/checkout@v3

    - name: Build with Maven
      run: mvn clean install -DskipTests
        
    - name: Run tests
      run: mvn test
        
    - name: Deploy to Maven repository
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "PACKAGE_TOKEN: $(echo ${{ secrets.PACKAGE_TOKEN }} | cut -c1-8)..."
        mvn deploy -DskipTests -X -U \
        -s ci_settings.xml -DrepositoryId=tvision360-releases \
        -Dmaven.deploy.skip=false -Dmaven.deploy.uniqueVersion=false
      env:
        PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}