name: openHAB CI

on:
  push:
    branches: [ main, '*' ]  # Run on all branches
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: localstack/java-maven-node-python

    steps:
    - uses: actions/checkout@v3

    - name: Build with Maven
      run: mvn clean install -DskipTests
        
    - name: Run tests
      run: mvn test
        
    - name: Deploy to Maven repository (Release)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "PACKAGE_TOKEN: $(echo ${{ secrets.PACKAGE_TOKEN }} | cut -c1-8)..."
        mvn deploy -DskipTests -X -U \
        -s ci_settings.xml -DrepositoryId=tvision360-releases \
        -Dmaven.deploy.skip=false -Dmaven.deploy.uniqueVersion=false
      env:
        PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

    - name: Deploy to Maven repository (Snapshot)
      if: github.event_name == 'push' && github.ref != 'refs/heads/main'
      run: |
        echo "PACKAGE_TOKEN: $(echo ${{ secrets.PACKAGE_TOKEN }} | cut -c1-8)..."
        mvn deploy -DskipTests -X -U \
        -s ci_settings.xml -DrepositoryId=tvision360-snapshots \
        -Dmaven.deploy.skip=false
      env:
        PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}