name: openHAB CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: maven:3.8.4-openjdk-11

    steps:
    - name: Install Node.js
      run: |
        apt-get update
        apt-get install -y curl
        curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        apt-get install -y nodejs
    
    - uses: actions/checkout@v3
    
    - name: Cache Maven packages
      run: |
        CACHE_KEY="${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}"
        if [ -d ~/.m2 ]; then
          tar -czf maven-repo.tar.gz -C ~ .m2
          gitea-release upload -f maven-repo.tar.gz -n "maven-repo-${CACHE_KEY}.tar.gz"
        fi

    - name: Restore Maven packages
      run: |
        CACHE_KEY="${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}"
        if gitea-release download -n "maven-repo-${CACHE_KEY}.tar.gz" -o maven-repo.tar.gz; then
          mkdir -p ~/.m2
          tar -xzf maven-repo.tar.gz -C ~
          rm maven-repo.tar.gz
        fi

    - name: Build with Maven
      run: mvn clean install -DskipTests
      env:
        MAVEN_REPO_URL: ${{ secrets.MAVEN_REPO_URL }}
        MAVEN_RELEASE_ENDPOINT: ${{ secrets.MAVEN_RELEASE_ENDPOINT }}
        MAVEN_SNAPSHOT_ENDPOINT: ${{ secrets.MAVEN_SNAPSHOT_ENDPOINT }}
        
    - name: Run tests
      run: mvn test
      
    - name: Deploy to Maven repository
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        mvn deploy -DskipTests \
        -Drepository.url=${{ secrets.MAVEN_REPO_URL }} \
        -Drepository.username=${{ secrets.MAVEN_REPO_USERNAME }} \
        -Drepository.password=${{ secrets.MAVEN_REPO_PASSWORD }}
      env:
        MAVEN_REPO_URL: ${{ secrets.MAVEN_REPO_URL }}
        MAVEN_RELEASE_ENDPOINT: ${{ secrets.MAVEN_RELEASE_ENDPOINT }}
        MAVEN_SNAPSHOT_ENDPOINT: ${{ secrets.MAVEN_SNAPSHOT_ENDPOINT }}