name: TVision360 CI

on:
  push:
    branches: [ main, '*' ]  # Run on all branches
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Run tests
      run: mvn test

    - name: Set version type
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "MAVEN_PROFILE=-Prelease"
        else
          echo "MAVEN_PROFILE=-Psnapshot"
        fi >> $GITHUB_ENV

    - name: Deploy to Maven repository
      run: |
        echo "PACKAGE_TOKEN: $(echo ${{ secrets.PACKAGE_TOKEN }} | cut -c1-8)..."
        mvn deploy -B -DskipTests ${{ env.MAVEN_PROFILE }}
      env:
        PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}

permissions:
  contents: read
  packages: write